services:
  postgres:
    image: postgres:18-alpine
    container_name: url-shortener-db
    environment:
      POSTGRES_USER: urlshortener
      POSTGRES_PASSWORD: urlshortener
      POSTGRES_DB: urlshortener
      PGDATA: /tmp/pgdata
    ports:
      - "5432:5432"
    tmpfs:
      - /tmp:rw,noexec,nosuid,size=1g
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U urlshortener"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres-test:
    image: postgres:18-alpine
    container_name: url-shortener-db-test
    environment:
      POSTGRES_USER: urlshortener
      POSTGRES_PASSWORD: urlshortener
      POSTGRES_DB: urlshortener_test
      PGDATA: /tmp/pgdata
    ports:
      - "5433:5432"
    tmpfs:
      - /tmp:rw,noexec,nosuid,size=1g
    command:
      - "postgres"
      - "-c"
      - "app.allow_nuke=true"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U urlshortener"]
      interval: 10s
      timeout: 5s
      retries: 5
    profiles:
      - test
